steps:
  - simple_align:
      cases: true
      top_level_patterns: true
      records: true

  - imports:
      align: global
      list_align: after_alias
      pad_module_names: true
      long_list_align: inline
      empty_list_align: inherit
      list_padding: 4
      separate_lists: false
      space_surround: false

  - language_pragmas:
      style: vertical
      align: true
      remove_redundant: true
      language_prefix: LANGUAGE

  # Remove trailing whitespace
  - trailing_whitespace: {}

columns: 92
newline: lf

language_extensions:
  - ConstraintKinds
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - MultiParamTypeClasses
  - OverloadedStrings
  - TypeFamilies
  - ViewPatterns

cabal: true
